#!/bin/sh

cd /tmp &&
rm -rf foo* &&
mkdir foo &&
cd foo &&

git init --template=/home/xen/src/gitback/templates/rpatterson-filemetadata/ &&
git config --replace-all gitback.pipeline 'cat >../foo-$(git rev-parse HEAD).bundle'
echo foo > foo.txt && git add . && git commit -m "Add a file" &&
git back || exit 1

objs=$( git list-unpacked commit tree blob )
if [[ -n $objs ]]
then
    echo Remaining objs: $objs
    exit 1
fi

for obj in .git/objects/??/
do
    if [[ -d $obj ]]
    then
        echo Remaining objs: $obj
        exit 1
    fi
done

for i in $( seq $1 )
do
    dd if=/dev/urandom count=2048 of=bar-$i.txt && git add . && echo "Add file $i" | git back-commit &&
    git back || exit 1

    objs=$( git list-unpacked back-commit tree blob )
    if [[ -n $objs ]]
    then
        echo Remaining objs: $objs
        exit 1
    fi

    for obj in .git/objects/??/
    do
        if [[ -d $obj ]]
        then
            echo Remaining objs: $obj
            exit 1
        fi
    done

done
git fsck

for bundle in $( ls -tr /tmp/foo-????????????????????????????????????????.bundle )
do
    echo >&2 "Restoring from $bundle ..."
    cp $bundle /tmp/foo.bundle
    if [[ ! -d /tmp/foo.restore ]]
    then
        cd /tmp
        git clone foo.bundle foo.restore || exit 1
        cd foo.restore
    fi
    git pull origin master || exit 1
done

cat foo.txt
ls -l bar-*.txt
git fsck
du -s /tmp/foo /tmp/foo.restore
