#!/bin/sh

cd /tmp &&
rm -rf foo* &&
mkdir foo &&
cd foo &&

git init --template=/home/xen/src/gitback/templates/rpatterson-filemetadata/ &&
echo foo > foo.txt && git add . && git commit -m "Add a file" &&
git rm-blobs master

blobs=$(echo blob | git list-objects --unpacked)
if [[ -n $blobs ]]
then
    echo Remaining blobs: $blobs
fi

while [[ 1 ]]
do
    echo bar >> foo.txt && git add . && git commit -m "Add a line" &&
    git rm-blobs master^..master

    blobs=$(echo blob | git list-objects --unpacked)
    if [[ -n $blobs ]]
    then
        echo Remaining blobs: $blobs
    fi
done

