#!/bin/sh

cd /tmp &&
rm -rf foo* &&
mkdir foo &&
cd foo &&

git init --template=/home/xen/src/gitback/templates/rpatterson-filemetadata/ &&
echo foo > foo.txt && git add . && git commit -m "Add a file" &&
git rm-blobs master || exit 1

objs=$( git list-unpacked commit tree blob )
if [[ -n $objs ]]
then
    echo Remaining objs: $objs
    exit 1
fi

for obj in .git/objects/??/
do
    if [[ -d $obj ]]
    then
        echo Remaining objs: $obj
        exit 1
    fi
done

for i in $( seq 10 )
do
    echo bar-$i >> foo.txt && git add . && git commit -m "Add line $i" &&
    git rm-blobs master^..master || exit 1

    objs=$( git list-unpacked commit tree blob )
    if [[ -n $objs ]]
    then
        echo Remaining objs: $objs
        exit 1
    fi

    for obj in .git/objects/??/
    do
        if [[ -d $obj ]]
        then
            echo Remaining objs: $obj
            exit 1
        fi
    done

done

