#!/bin/sh
#
# Copyright (c) 2009 Ross Patterson

USAGE='[--unpacked] <git-rev-list args>... <type...'
LONG_USAGE='List SHA1 hashes for objects of the given in the object store.'
SUBDIRECTORY_OK=Yes
. $(git --exec-path)/git-sh-setup

read types

for rev in $(
    git rev-list --objects "$@" |
    grep -o '^[[:alnum:]]\{40\}' )
do
    for type in $types
    do
        if [[ $(git cat-file -t $rev) == $type ]]
        then echo $rev
        fi
    done
done
