#!/bin/sh
#
# Copyright (c) 2009 Ross Patterson

USAGE=''
LONG_USAGE='Backup the repository using to the pipeline configured \
in the gitback.pipeline git-config option'
SUBDIRECTORY_OK=Yes
. $(git --exec-path)/git-sh-setup

require_work_tree
TAG=archived
set_reflog_action "$TAG"

if [[ -n $( git tag -l $TAG ) ]]
then
    revlist=$TAG..master
else
    revlist=master
fi

pipeline=$( git config --get gitback.pipeline )

## Create the bundle since the last archving
echo >&2 "Creating and archiving the bundle..."
git bundle create - $revlist |
## Pipe the bundle into the command given in the arguents to archive
## it on the offsite backups
eval $pipeline || (
    die "Failed to upload bundle" )

echo >&2 "Set the tag..."
git tag -f $TAG master || (
    die "Failed to updagte the archive tag" )

echo >&2 "Remove blobs..."
git rm-blobs || (
    die "Failed remove blobs from the local store" )
