#!/bin/sh
#
# Copyright (c) 2009 Ross Patterson

USAGE=''
LONG_USAGE='Backup the repository using to the pipeline configured \
in the gitback.pipeline git-config option'
SUBDIRECTORY_OK=Yes
. $(git --exec-path)/git-sh-setup

require_work_tree
$TAG = archived
set_reflog_action "$TAG"

$revlist = $TAG..master
## If I want to take an arg
# $revlist = $1

pipeline =  $( git config --get gitback.pipeline )

## Create the bundle since the last archving
git bundle create -- $revlist |
## Pipe the bundle into the command given in the arguents to archive
## it on the offsite backups
eval || (
     die "Failed to upload bundle" )

git tag -f $TAG master || (
    die "Failed to updagte the archive tag" )

git rm-blobs $revlist || (
    die "Failed remove blobs from the local store" )
